### ISSUE TITLE
Playback with promethion bulk data

### ISSUE THREAD

**Issue by DanteV19** [W-L/simION#2]
Thanks to your well-documented code, I could run playback within a container using the MinION bulk file from readfish.
I would like to run playback with the PromethION bulk file instead too.

However, I could not run the playback using the PromethION bulk file with the current toml and I suspect the toml from:
_/opt/ont/minknow/conf/package/sequencing/sequencing_MIN114_DNA_e8_2_400K.toml_
is a toml specifically meant for MinION bulk file. However, I do not see any way on how to configure using another toml like sequencing_PRO114* for PromethION. So far, the playback seems to use sequencing_MIN114_DNA_e8_2_400K.toml by default. 

Which adjustments should I make to be able to use the right toml file for the simulated PromethION device?

**Comment by W-L** [comment]
Hi Dante,
The code in this project is quite specific to my setup. So I hard-coded the sequencing protocol that I use to run the playback into the script that launches the protocol. This is the file https://github.com/W-L/simION/blob/main/code/start_protocol_mod.py and the hard-coded line is 620. You could either change the protocol there or delete that line and see if the script detects the necessary protocol by itself. I just wanted to make sure that it always uses the same one, that's why I hardcoded it there.

**Comment by DanteV19** [comment]
Thanks for your feedback.
I have changed the hard coded line at 620 to:
`prot = "sequencing/sequencing_PRO114_DNA_e8_2_400K:FLO-PRO114:SQK-LSK114:400"`
and added the path to the prom bulk file in _sequencing_PRO114_DNA_e8_2_400K.toml_.

But that could not get it to work till I changed and added some lines in [https://github.com/W-L/simION/blob/main/code/launch_playback.sh](https://github.com/W-L/simION/blob/main/code/launch_playback.sh):

- Change line 9 to `/opt/ont/minknow/bin/mk_manager_svc -c /opt/ont/minknow/conf --simulated-integrated-devices=1 -d &`
- Add another line before line 12 `bash /opt/ont/minknow/bin/add_simulated_prom.sh`
- Change position _MS00000_ to _A1_

The last two changes were needed because it does not automatically create a PromethION simulated device when necessary unlike MinION simulated device.

With your feedback including the additional changes I finally got playback working for PromethION bulk data!

I will close this since this issue has been fixed (unless it is not github protocol then please reopen if you got any questions or comments).
